# Random numbers and counting outcomes

We introduce numpy's random number functions and a few advanced data types that we can use to count and order outcomes. This will all be very useful if we want to simulate dices rolls, coin tosses, dealing cards, spinning roulette wheels and other games of chance.

Note - several of you may have already discovered Python's random numger generation through the `math` packaage. That's fine, but you may want to consider using numpy instead due to its wider use and stronger developer community.

In [26]:
from collections import Counter
from collections import OrderedDict
import numpy as np

## Sampling random integers

To generate a numpy array (behaves just like a list) of random integers, use `np.random.randint(min, max, count)` where `min` is inclusive, `max` is exclusive and `count` is the number of random integers.

In [27]:
# Simulating 20 rolls of a 4-sided die
rolls = np.random.randint(1,5,20)
print(type(rolls))
print(rolls)

<class 'numpy.ndarray'>
[2 4 4 4 4 3 4 4 2 1 3 4 3 4 4 1 4 3 3 4]


In [28]:
# Simulating 15 rolls of a 20-sided die
rolls = np.random.randint(1,21,15)
print(rolls)

[ 9  3  4  7 11 15 19  5  1 19 11 18  8 20  9]


One of the cool features of numpy arrays is that we can do operations element-by-element on arrays of the same size. This is something you can't do with regular Python lists.

In [29]:
trial1 = np.random.randint(1,21,10)
trial2 = np.random.randint(1,21,10)
trial_sum = trial1 + trial2 # We're adding arrays.
print(trial1)
print(trial2)
print(trial_sum)

print()
for a, b, c in zip(trial1, trial2, trial_sum):
    print(a, '+', b, '=', c)

[11  6 13  9 19 15  2  1  8 11]
[ 6  3  9  9 11  4 19 10  8 11]
[17  9 22 18 30 19 21 11 16 22]

11 + 6 = 17
6 + 3 = 9
13 + 9 = 22
9 + 9 = 18
19 + 11 = 30
15 + 4 = 19
2 + 19 = 21
1 + 10 = 11
8 + 8 = 16
11 + 11 = 22


## Sampling random floating point numbers

To generate a numpy array (behaves just like a list) of random numbers between zero and one from a uniform distribution, use `np.random.random(count)`

In [30]:
outcomes = np.random.random(20)
print(outcomes)

[0.69023378 0.66367513 0.59948823 0.35472024 0.15875959 0.00486269
 0.7030124  0.36318915 0.04287805 0.76755714 0.33015025 0.5308122
 0.13441247 0.35280335 0.48057904 0.81072707 0.65727538 0.43985643
 0.53838583 0.25486441]


To sample over a different range, say 0-10 rather than 0-1, just scale your results. Numpy arrays allow you to apply operation to all elements of the array at once.

In [31]:
outcomes = 10 * np.random.random(20)
print(outcomes)

[3.85378882 3.61174024 4.26516077 2.05037402 2.9578402  0.54820592
 7.20908561 1.35257311 5.26402969 2.55247425 3.53982308 1.86077015
 1.52881671 9.37192773 9.3210281  1.63216244 5.48229731 0.16696376
 4.61525036 7.62199562]


## Sampling from a collection of items

Use `np.random.choice(a)` to random select an element from a collection of items (list, numpy array, set). Add `size=n` to specify the number of samples and `replace=False` to do sampling without replacement.

In [32]:
mylist = ['A', 'B', 'C', 'D', 'E', 'F']

In [33]:
# Sample a single random item from mylist
x = np.random.choice(mylist)
print(x)

D


In [34]:
# Sample 10 random items from mylist
# Note that replacements are allowed
x = np.random.choice(mylist, size=10)
print(x)

['A' 'C' 'E' 'D' 'B' 'D' 'E' 'F' 'E' 'D']


In [35]:
# Sample 5 random items from mylist without replacement
# NOTE - this is equivalent to a random combination 7-choose-5
x = np.random.choice(mylist, size=5, replace=False)
print(x)

['C' 'A' 'B' 'E' 'D']


## Exercises

Do the following exercies

(1) Simulate 50 rolls of an 8-sided die

(2) Simulate 20 rolls of a 7-sided die

(3) Roll the following handful of dice 20 times and calculate the sum for each outcome:

+ One 4-sided die
+ Two 6-sided dice
+ Three 8-sided dice

See earlier example where we directly added numpy arrays.

As a bonus, see if you can generate the following output (your numbers will vary). Hint, you may want to use the zip function like we did earlier.

+ 4-sided: 3 + 6-sided: 4 5 + 8-sided: 4 6 8 = 30
+ 4-sided: 1 + 6-sided: 4 2 + 8-sided: 3 5 1 = 16
+ ...

(4) Generate random samples of the letters A-D with and without replacement. What happens if you try to sample too many items when not allowing replacement?

(5) Bonus - either using stackoverflow or the Python help (`np.random.choice?`), see if you can figure out how to do random sampling with uneven probabilities. For example, 

A: 10%, B: 20%, C: 30%, D: 40%

## Counting outcomes

What if we want to keep track of how many times each outcome occurs? We can use the functionality that we imported at the top of the notebook.

```python
from collections import Counter
from collections import OrderedDict
```

In [39]:
rolls = np.random.randint(1,5,2000)
print(rolls)
counts = Counter(rolls)

[1 1 1 ... 1 2 3]


In [40]:
print(counts)
print()
for key,value in counts.items():
    print(key, value)

Counter({3: 538, 4: 513, 1: 488, 2: 461})

1 488
4 513
3 538
2 461


To sort the results, use the OrderedDict and the example below

In [41]:
# Dense piece of code - I had to look this up
od = OrderedDict(sorted(counts.items()))
print(od)

for x, y in zip(od.keys(), od.values()):
    print(x, y)

OrderedDict([(1, 488), (2, 461), (3, 538), (4, 513)])
1 488
2 461
3 538
4 513
